// Generated by BUCKLESCRIPT VERSION 1.7.4, PLEASE EDIT WITH CARE
'use strict';

import * as $dot$slashmath$dotjs from "./math.js";

function print(x) {
  console.log($dot$slashmath$dotjs.sub(x, x));
  return /* () */0;
}

export {
  print ,
  
}
/* ./math.js Not a pure module */
