// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

import * as Add from "./add.js";
import * as Dec from "./dec";

function fib(n) {
  var _n = n;
  var _a = 1;
  var _b = 1;
  while(true) {
    var b = _b;
    var a = _a;
    var n$1 = _n;
    if (n$1) {
      _b = Add.add(a, b);
      _a = b;
      _n = Dec.dec(n$1);
      continue ;
      
    } else {
      return a;
    }
  };
}

export {
  fib ,
  
}
/* ./dec Not a pure module */
